# Generated by Django 2.1 on 2018-09-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20180901_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(default='photos_cars/photo_car_default.png', upload_to='photos_cars/%d'),
        ),
    ]
