# Generated by Django 2.1 on 2018-09-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_auto_20180901_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='enrollment',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
