# Generated by Django 2.1 on 2018-09-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('cellphone', models.CharField(max_length=12)),
                ('age', models.IntegerField()),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('photo', models.ImageField(default='photos/photo_default.jpg', upload_to='photos/%d')),
            ],
        ),
    ]
