# Generated by Django 2.1 on 2018-09-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_auto_20180901_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='photo',
            field=models.ImageField(default='photos/photo_default.jpg', upload_to='photos/%d'),
        ),
    ]
