# Generated by Django 2.1 on 2018-09-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_auto_20180901_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='document',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='photo',
            field=models.ImageField(blank=True, default='/photos/photo_default.jpg', upload_to='photos/%d'),
        ),
    ]
